---
name: Update the readme.md file with the number of stars in AoC challenges
on:
  push:
    paths:
      - ".github/workflows/update_readme_stars.yaml"
      - "vscode_tasks/update_readme_stars.py"
      - "year/**.py"
      - "readme.md"
jobs:
  update-readme-stars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Execute update_readme_stars.py script
        run: python vscode_tasks/update_readme_stars.py
      - name: Git commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if git commit -am "Update stars in readme.md file" ; then
            git push origin HEAD:${{ github.ref }}
          fi
